apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::243725898248:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::243725898248:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D2FZ2H02J2QQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-17T06:28:34Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-04-17T06:28:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1506"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c121defc-5bfb-4e62-ba1f-f5124b11a6e5
